Repository jsk-ros-pkg/jsk_common, pull requests merged in 2022-06, with the labels that each got.

#1734 Loose test failed
  jsk_data/tests/test_data_collection_server.py
  jsk_topic_tools/test/test_connection.py
  jsk_topic_tools/test/test_connection_based_nodelet.test
  jsk_topic_tools/test/test_connection_based_transport.test
  jsk_topic_tools/test/test_stealth_relay.py
  jsk_topic_tools/test/test_stealth_relay.test
  jsk_topic_tools/test/test_topic_buffer_fixed_rate.test
Labels: MergeOK_if_CI_passed

#1725 Add test for topic connection test after killing nodes
  jsk_tools/src/test_topic_published.py
  jsk_tools/test/test_topic_published.launch
  jsk_topic_tools/test/test_synchronized_throttle.test
Labels: bug, MergeOK, test

#1736 [jsk_topic_tools] Fix the default vital rate in doc
  doc/jsk_topic_tools/class/diagnostic_nodelet.md
Labels: MergeOK_if_CI_passed

#1731 [virtual_force_publisher] Calcualte sr-inverse
  virtual_force_publisher/src/virtual_force_publisher.cpp
Labels: MergeOK_if_CI_passed

#1699 [jsk_topic_tools] add rostopic_connection_list
  doc/jsk_topic_tools/scripts/rostopic_connection_list.md
  jsk_topic_tools/scripts/rostopic_connection_list
Labels: MergeOK_if_CI_passed

#1740 [jsk_topic_tools/connection_based_transport] Update the time of last_published_time
  doc/jsk_topic_tools/class/python_connection_based_transport.md
  jsk_topic_tools/src/jsk_topic_tools/transport.py
Labels: enhancement, doc

#1709 [jsk_topic_tools] add non static_tf mode to static_tf_republisher
  doc/jsk_topic_tools/scripts/static_tf_republisher.rst
  jsk_topic_tools/CMakeLists.txt
  jsk_topic_tools/sample/config/sample_static_tf_republisher.rviz
  jsk_topic_tools/sample/data/.gitignore
  jsk_topic_tools/sample/sample_static_tf_republisher.launch
  jsk_topic_tools/scripts/static_tf_republisher.py
  jsk_topic_tools/test/test_static_tf_republisher.py
  jsk_topic_tools/test/test_static_tf_republisher.test
Labels: question, WaitForReview

#1743 [jsk_topic_tools/HzMeasureNodelet] Add diagnostics to monitor hz
  doc/jsk_topic_tools/class/hz_measure_nodelet.md
  jsk_topic_tools/include/jsk_topic_tools/hz_measure_nodelet.h
  jsk_topic_tools/src/hz_measure_nodelet.cpp
Labels: enhancement, doc

#1744 [jsk_tools/test_topic_published.py] Add condition_%d option for checking topic value
  doc/jsk_tools/test_nodes/test_topic_published.rst
  jsk_tools/src/test_topic_published.py
  jsk_tools/test/test_topic_published.launch
Labels: enhancement, doc

#1745 [jsk_tools] Seperate sanity check frequency and diagnostics publish frequency
  doc/jsk_tools/scripts/sanity_diagnostics.md
  jsk_tools/sample/sample_sanity_diagnostics.launch
  jsk_tools/src/sanity_diagnostics.py
Labels: enhancement

#1706 Add boolean operation nodes (and, or, not)
  doc/jsk_topic_tools/scripts/boolean_node.rst
  jsk_topic_tools/CMakeLists.txt
  jsk_topic_tools/sample/sample_boolean_node.launch
  jsk_topic_tools/scripts/boolean_node.py
  jsk_topic_tools/test/test_boolean_node.test
Labels: WaitForFeedback
